<?php

namespace App\Http\Controllers;

use App\Models\Alumni;
use Illuminate\Http\Request;

class AlumniController extends Controller
{
    public function index()
        {
                $alumni = Alumni::all();
                        return view('alumni.index', compact('alumni'));
                            }

                                public function create()
                                    {
                                            return view('alumni.create');
                                                }

                                // Store method untuk form web (admin)
                                public function store(Request $request)
                                {
                                        $request->validate([
                                                'nama_lengkap'            => 'required|string|max:255',
                                                'tahun_lulus'             => 'required|integer',
                                                'no_wa'                   => 'required|string|max:20',
                                                'jurusan'                 => 'required|string|max:255',

                                                'metode_pengiriman_kta'   => 'required|string|max:255',
                                                'jumlah_kta'              => 'required|integer',

                                                'pas_foto'                => 'required|image|mimes:jpg,jpeg,png|max:2048',
                                                'bukti_transfer_kta'      => 'required|image|mimes:jpg,jpeg,png|max:2048',

                                                'bersedia_donasi'         => 'required|string',

                                                'jumlah_donasi'           => 'nullable|integer',
                                                'bukti_transfer_donasi'   => 'nullable|image|mimes:jpg,jpeg,png|max:2048',
                                        ]);

                                        // Upload file
                                        $pasFotoPath = $request->file('pas_foto')->store('pas_foto', 'public');
                                        $buktiKtaPath = $request->file('bukti_transfer_kta')->store('bukti_kta', 'public');

                                        $buktiDonasiPath = null;
                                        if ($request->hasFile('bukti_transfer_donasi')) {
                                                $buktiDonasiPath = $request->file('bukti_transfer_donasi')->store('bukti_donasi', 'public');
                                        }

                                        $data = [
                                                'nama_lengkap'            => $request->input('nama_lengkap'),
                                                'tahun_lulus'             => $request->input('tahun_lulus'),
                                                'angkatan'                => $request->input('angkatan', $request->input('tahun_lulus')),
                                                'alamat'                  => $request->input('alamat', ''),
                                                'no_wa'                   => $request->input('no_wa', ''),
                                                'jurusan'                 => $request->input('jurusan', ''),

                                                'metode_pengiriman_kta'   => $request->input('metode_pengiriman_kta', null),
                                                'jumlah_kta'              => $request->input('jumlah_kta', null),

                                                'pas_foto'                => $pasFotoPath,
                                                'bukti_transfer_kta'      => $buktiKtaPath,

                                                'bersedia_donasi'         => $request->input('bersedia_donasi', null),
                                                'jumlah_donasi'           => $request->input('jumlah_donasi', null),
                                                'bukti_transfer_donasi'   => $buktiDonasiPath,
                                        ];

                                        Alumni::create($data);

                                        return redirect()->route('alumni.index')->with('success', 'Data berhasil ditambahkan');
                                }

                                                    public function storeApi(Request $request)
                                                        {
                                                                $request->validate([
                                                                            'nama_lengkap'            => 'required|string|max:255',
                                                                                        'tahun_lulus'             => 'required|integer',
                                                                                                    'no_wa'                   => 'required|string|max:20',
                                                                                                                'jurusan'                 => 'required|string|max:255',

                                                                                                                            'metode_pengiriman_kta'   => 'required|string|max:255',
                                                                                                                                        'jumlah_kta'              => 'required|integer',

                                                                                                                                                    'pas_foto'                => 'required|image|mimes:jpg,jpeg,png|max:2048',
                                                                                                                                                                'bukti_transfer_kta'      => 'required|image|mimes:jpg,jpeg,png|max:2048',

                                                                                                                                                                            'bersedia_donasi'         => 'required|string',

                                                                                                                                                                                        'jumlah_donasi'           => 'nullable|integer',
                                                                                                                                                                                                    'bukti_transfer_donasi'   => 'nullable|image|mimes:jpg,jpeg,png|max:2048',
                                                                                                                                                                                                            ]);

                                                                                                                                                                                                                    // Upload file
                                                                                                                                                                                                                            $pasFotoPath = $request->file('pas_foto')->store('pas_foto', 'public');
                                                                                                                                                                                                                                    $buktiKtaPath = $request->file('bukti_transfer_kta')->store('bukti_kta', 'public');

                                                                                                                                                                                                                                            $buktiDonasiPath = null;
                                                                                                                                                                                                                                                    if ($request->hasFile('bukti_transfer_donasi')) {
                                                                                                                                                                                                                                                                $buktiDonasiPath = $request->file('bukti_transfer_donasi')->store('bukti_donasi', 'public');
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                $dataApi = [
                                                                                                                                                                                                                                                                                                        'nama_lengkap'            => $request->input('nama_lengkap'),
                                                                                                                                                                                                                                                                                                                                'tahun_lulus'             => $request->input('tahun_lulus'),
                                                                                                                                                                                                                                                                                                                                'angkatan'                => $request->input('angkatan', $request->input('tahun_lulus')),
                                                                                                                                                                                                                                                                                                                                'alamat'                  => $request->input('alamat', ''),
                                                                                                                                                                                                                                                                                                                                                        'no_wa'                   => $request->input('no_wa', ''),
                                                                                                                                                                                                                                                                                                                                                                                'jurusan'                 => $request->input('jurusan', ''),

                                                                                                                                                                                                                                                                                                                                                                                                        'metode_pengiriman_kta'   => $request->input('metode_pengiriman_kta', null),
                                                                                                                                                                                                                                                                                                                                                                                                                'jumlah_kta'              => $request->input('jumlah_kta', null),

                                                                                                                                                                                                                                                                                                                                                                                        'pas_foto'                => $pasFotoPath,
                                                                                                                                                                                                                                                                                                                                                                                                                'bukti_transfer_kta'      => $buktiKtaPath,

                                                                                                                                                                                                                                                                                                                                                                                                        'bersedia_donasi'         => $request->input('bersedia_donasi', null),
                                                                                                                                                                                                                                                                                                                                                                                                                'jumlah_donasi'           => $request->input('jumlah_donasi', null),
                                                                                                                                                                                                                                                                                                                                                                                                                'bukti_transfer_donasi'   => $buktiDonasiPath,
                                                                                                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                                                                                        Alumni::create($dataApi);

                                                                                                                                                                                                                                                                                                                                                                                                                                    return redirect()->route('alumni.index')->with('success', 'Data berhasil ditambahkan');
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                            public function edit($id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        $alumni = Alumni::findOrFail($id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return view('alumni.edit', compact('alumni'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public function update(Request $request, $id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $request->validate([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'nama_lengkap'            => 'required|string|max:255',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'tahun_lulus'             => 'required|integer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'no_wa'                   => 'required|string|max:20',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'jurusan'                 => 'required|string|max:255',

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'metode_pengiriman_kta'   => 'required|string|max:255',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'jumlah_kta'              => 'required|integer',

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'pas_foto'                => 'nullable|image|mimes:jpg,jpeg,png|max:2048',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'bukti_transfer_kta'      => 'nullable|image|mimes:jpg,jpeg,png|max:2048',

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'bersedia_donasi'         => 'required|string',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'jumlah_donasi'           => 'nullable|integer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'bukti_transfer_donasi'   => 'nullable|image|mimes:jpg,jpeg,png|max:2048',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $alumni = Alumni::findOrFail($id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Build update data with current values as fallback
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $data = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'nama_lengkap' => $request->input('nama_lengkap', $alumni->nama_lengkap),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'tahun_lulus' => $request->input('tahun_lulus', $alumni->tahun_lulus),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'angkatan' => $request->input('angkatan', $request->input('tahun_lulus', $alumni->tahun_lulus)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'alamat' => $request->input('alamat', $alumni->alamat ?? ''),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'no_wa' => $request->input('no_wa', $alumni->no_wa ?? ''),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'jurusan' => $request->input('jurusan', $alumni->jurusan ?? ''),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'metode_pengiriman_kta' => $request->input('metode_pengiriman_kta', $alumni->metode_pengiriman_kta ?? null),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'jumlah_kta' => $request->input('jumlah_kta', $alumni->jumlah_kta ?? null),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'bersedia_donasi' => $request->input('bersedia_donasi', $alumni->bersedia_donasi ?? null),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'jumlah_donasi' => $request->input('jumlah_donasi', $alumni->jumlah_donasi ?? null),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Handle file uploads and set into data array
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ($request->hasFile('pas_foto')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $data['pas_foto'] = $request->file('pas_foto')->store('pas_foto', 'public');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ($request->hasFile('bukti_transfer_kta')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $data['bukti_transfer_kta'] = $request->file('bukti_transfer_kta')->store('bukti_kta', 'public');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ($request->hasFile('bukti_transfer_donasi')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $data['bukti_transfer_donasi'] = $request->file('bukti_transfer_donasi')->store('bukti_donasi', 'public');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $alumni->update($data);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return redirect()->route('alumni.index')->with('success', 'Data berhasil diperbarui');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public function destroy($id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Alumni::destroy($id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return redirect()->route('alumni.index')->with('success', 'Data alumni berhasil dihapus!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            